### ISSUE TITLE
Error in .f(.x[[i]], ...) : object 'TOPONIMIA' not found

### ISSUE THREAD

**Issue by MirelSIG** [maestria-geotel-201902/unidad-2-asignacion-1-esda-operaciones-con-atributos-plots-MirelSIG#1]
Entiendo que TOPONIMIA no es un objeto sino el nombre de un campo, pero ese script no da para que yo pueda incorporar elementos q generen error... Estoy omitiendo la creación de ese objeto q no encuentra en sentencias anteriores que no logro ver?

![image](https://user-images.githubusercontent.com/39567020/68584171-3ec43a00-0455-11ea-9efa-c4fd60075f70.png)

**Comment by lodurr** [comment]
Hola, lo lograste resolver?? Tocaría ver que sentencia pusiste antes del colnames(prov) por que antes de eso ya tienes el error con la Toponimia.

**Comment by MirelSIG** [comment]
Gracias Diego, ya pude correrlo

**Comment by lodurr** [comment]
No olvides cerrar el issue, asi se puede ver que ya no es necesaria la ayuda


![imagen](https://user-images.githubusercontent.com/1824882/68866059-388ac380-06ca-11ea-991c-7e0075ff544e.png)

**Comment by geofis** [comment]
@MirelSIG @lodurr Reabriendo sólo para opinar, disculpen.

'Ta bonito este issue, porque la OP (*original poster*) planteó y pudo resolverlo por su cuenta posteriormente.
